Fix compile error
Fixed this error: actual and formal argument lists differ in length

> Task :compileJava
/Users/dennch3/temp/vertx-examples/http2-showcase/src/main/java/io/vertx/examples/http2/Http2ServerVerticle.java:78: error: method create in interface HandlebarsTemplateEngine cannot be applied to given types;
        HandlebarsTemplateEngine engine = HandlebarsTemplateEngine.create();
                                                                  ^
  required: Vertx
  found: no arguments
  reason: actual and formal argument lists differ in length